import os

PLAIN_HTTP = (os.environ.get("PLAIN_HTTP", "no").lower() == "yes")
SERVER_PORT = int(os.environ.get("SERVER_PORT", "12000"))
INCLUDE_USAGE_STATISTICS = (os.environ.get("INCLUDE_USAGE_STATISTICS", "no").lower() == "yes")
USAGE_STATISTICS_MAX_SAMPLES = int(os.environ.get("USAGE_STATISTICS_MAX_SAMPLES", "1000"))

OPENEHR_API_BASE_URI = os.environ.get("OPENEHR_API_BASE_URI", "http://127.0.0.1:12003/ehrbase/rest/openehr")
VALIDATE_OPENEHR_API_CERTIFICATE = (os.environ.get("VALIDATE_OPENEHR_API_CERTIFICATE", "no") == "yes")
USE_CUSTOM_OPENEHR_API_CA_CERTIFICATE = (os.environ.get("USE_CUSTOM_OPENEHR_API_CA_CERTIFICATE", "no") == "yes")

DEMOGRAPHIC_API_BASE_URI = os.environ.get("DEMOGRAPHIC_API_BASE_URI", "http://127.0.0.1:12002")
VALIDATE_DEMOGRAPHIC_API_CERTIFICATE = (os.environ.get("VALIDATE_DEMOGRAPHIC_API_CERTIFICATE", "no") == "yes")
USE_CUSTOM_DEMOGRAPHIC_API_CA_CERTIFICATE = (os.environ.get("USE_CUSTOM_DEMOGRAPHIC_API_CA_CERTIFICATE", "no") == "yes")

PROV_API_BASE_URI = os.environ.get("PROV_API_BASE_URI", "http://127.0.0.1:12001")
VALIDATE_PROV_API_CERTIFICATE = (os.environ.get("VALIDATE_PROV_API_CERTIFICATE", "no") == "yes")
USE_CUSTOM_PROV_API_CA_CERTIFICATE = (os.environ.get("USE_CUSTOM_PROV_API_CA_CERTIFICATE", "no") == "yes")
